### ISSUE TITLE
Spelling mistake in demo files that may affect file use: generalPratitioner missing a "c"

### ISSUE THREAD

**Issue by mmorrissey-isc** [chronic-care/sample-data#1]
There is a spelling mistake in cc-betsy-1-demographic.json on line 2697 that may affect file use:
Current:
generalPratitioner 

Proposed
generalPractitioner 

It's also in cc-david-1-demographic.json

**Comment by drdavec** [comment]
Thanks for your report!  This typo has been fixed along with many other updates.
